### ISSUE TITLE
mass load speedup

### ISSUE THREAD

**Issue by jonny64** [gallyamow/fias-gar-sql-converter#1]
should COPY FROM STDIN ... FORMAT csv greatly improve bulk load perfomance compared to single INSERT's?
https://www.postgresql.org/docs/9.6/sql-copy.html

**Comment by gallyamow** [comment]
Hi, of course it does. But I have no time to implement at now. You also can use my new more powerful util - https://github.com/gallyamow/go-fias-exporter to do so.
