### ISSUE TITLE
PATH лучше импортировать, чем игнорировать

### ISSUE THREAD

**Issue by c0de9en** [gallyamow/fias-gar-sql-converter#2]
Есть в контрибах постгреса тип LTREE, который очень похож на PATH, индексируется и работает очень быстро, позволяет избавиться от рекурсивных запросов. Поскольку в дистрибутив этот тип не включён, затачивать под него XSD не нужно. Однако, импортировать PATH в поле типа TEXT или VARCHAR не помешает.

Дополнительный бонус - можно убрать из репы каталог gar_schemas, поскольку он отличается от ГАР только отсутствием поля PATH.

Не знаю, насколько хорош этот патч, у меня сработало:
```diff --git a/create-table.xslt b/create-table.xslt
index 64532b0..0ab19f3 100644
--- a/create-table.xslt
+++ b/create-table.xslt
@@ -77,6 +77,8 @@
                     <xsl:when test="@type='xs:boolean'">BOOLEAN</xsl:when>
 
                     <xsl:when test="contains(lower-case(xs:annotation/xs:documentation),'uuid')">UUID</xsl:when>
+
+                    <xsl:when test="@name='PATH'">VARCHAR</xsl:when>
                 </xsl:choose>
                 <xsl:if test="@use='required'">
                     <xsl:text> NOT NULL</xsl:text>
```

**Comment by gallyamow** [comment]
Ранее в ГАР не было поля path. Я тоже использовал LTREE, заполняя его рекурсивно.
Позже я добавлю ваш патч.

**Comment by gallyamow** [comment]
merged
